// Courses

export const 
    COURSE_NEW = '@@quizzical/COURSE_NEW',
    COURSE_LIST_REQUEST = '@@quizzical/COURSE_LIST_REQUEST',
    COURSE_LIST_RECEIVE = '@@quizzical/COURSE_LIST_RECEIVE',
    COURSE_EDIT = '@@quizzical/COURSE_EDIT',
    COURSE_REQUEST = '@@quizzical/COURSE_REQUEST',
    COURSE_RECEIVE = '@@quizzical/COURSE_RECEIVE',
    COURSE_UPDATE = '@@quizzical/COURSE_UPDATE',
    COURSE_FETCH = '@@quizzical/COURSE_FETCH',

    // Questions
    QUESTION_NEW = '@@quizzical/QUESTION_NEW',
    QUESTION_LIST_REQUEST = '@@quizzical/QUESTION_LIST_REQUEST',
    QUESTION_LIST_RECEIVE = '@@quizzical/QUESTION_LIST_RECEIVE',
    QUESTION_DELETE_PROMPT = '@@quizzical/QUESTION_DELETE_PROMPT',
    QUESTION_DELETE_CONFIRM = '@@quizzical/QUESTION_DELETE_CONFIRM',
    QUESTION_DELETE_CANCEL = '@@quizzical/QUESTION_DELETE_CANCEL',
    QUESTION_RECEIVE = '@@quizzical/QUESTION_RECEIVE',
    QUESTION_DELETE = '@@quizzical/QUESTION_DELETE',
    QUESTION_UPDATE = '@@quizzical/QUESTION_UPDATE',
    QUESTION_EDIT = '@@quizzical/QUESTION_EDIT',
    QUESTION_SAVE = '@@quizzical/QUESTION_SAVE',
    QUESTION_ANSWER_ADD = '@@quizzical/QUESTION_ANSWER_ADD',
    QUESTION_ANSWER_DELETE = '@@quizzical/QUESTION_ANSWER_DELETE',
    QUESTION_ANSWER_UPDATE = '@@quizzical/QUESTION_ANSWER_UPDATE',

    // Learning
    LEARN_PRACTICE_START = '@@quizzical/LEARN_PRACTICE_START',
    LEARN_PRACTICE_QUESTION_RECEIVE = '@@quizzical/LEARN_PRACTICE_QUESTION_RECEIVE',
    LEARN_PRACTICE_QUESTION_UPDATE_ANSWER = '@@quizzical/LEARN_PRACTICE_QUESTION_UPDATE_ANSWER',
    LEARN_PRACTICE_QUESTION_SUBMIT = '@@quizzical/LEARN_PRACTICE_QUESTION_SUBMIT',

    // Users
    USER_LIST_RECEIVE = '@@quizzical/USER_LIST_RECEIVE',
    USER_NEW = '@@quizzical/USER_NEW',
    USER_RECEIVE = '@@quizzical/USER_RECEIVE',
    USER_UPDATE = '@@quizzical/USER_UPDATE',
    USER_LOGIN_SUCCESS = '@@quizzical/USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE = '@@quizzical/USER_LOGIN_FAILURE',
    USER_LOGOUT = '@@quizzical/USER_LOGOUT',

    PAGINATION_UPDATE = '@@quizzical/PAGINATION_UPDATE';